// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteAnnotation(arg1) {
  return window['go']['main']['App']['DeleteAnnotation'](arg1);
}

export function ExportAnnotations(arg1) {
  return window['go']['main']['App']['ExportAnnotations'](arg1);
}

export function GetUI() {
  return window['go']['main']['App']['GetUI']();
}

export function ImportAnnotations(arg1) {
  return window['go']['main']['App']['ImportAnnotations'](arg1);
}

export function LoadAnnotations(arg1) {
  return window['go']['main']['App']['LoadAnnotations'](arg1);
}

export function OpenDataDir() {
  return window['go']['main']['App']['OpenDataDir']();
}

export function OpenDocument() {
  return window['go']['main']['App']['OpenDocument']();
}

export function OpenDocumentPath(arg1) {
  return window['go']['main']['App']['OpenDocumentPath'](arg1);
}

export function OpenExternal(arg1) {
  return window['go']['main']['App']['OpenExternal'](arg1);
}

export function SaveAnnotation(arg1) {
  return window['go']['main']['App']['SaveAnnotation'](arg1);
}

export function SetUI(arg1) {
  return window['go']['main']['App']['SetUI'](arg1);
}
