// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {models} from '../models';

export function DeleteAnnotation(arg1:string):Promise<void>;

export function ExportAnnotations(arg1:string):Promise<string>;

export function GetUI():Promise<string>;

export function ImportAnnotations(arg1:string):Promise<main.ImportResult>;

export function LoadAnnotations(arg1:string):Promise<Array<models.Annotation>>;

export function OpenDataDir():Promise<void>;

export function OpenDocument():Promise<models.Document>;

export function OpenDocumentPath(arg1:string):Promise<models.Document>;

export function OpenExternal(arg1:string):Promise<void>;

export function SaveAnnotation(arg1:models.Annotation):Promise<models.Annotation>;

export function SetUI(arg1:string):Promise<void>;
